version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    depends_on:
      - runner
  runner:
    image: 'gitlab/gitlab-runner:latest'