version: '3.8'
services:
  web:
    hostname: web
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    ports:
      - '80:80'
      - '8443:443'
      - '8022:22'
    depends_on:
      - runner
  runner:
    hostname: runner
    build:
      dockerfile: runner/Dockerfile
    volumes:
      - shared:/shared
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  shared: